#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
if git rev-parse --verify HEAD >/dev/null 2>&1
then
 against=HEAD
else
 # Initial commit: diff against an empty tree object
 against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)
# Redirect output to stderr.
exec 1>&2
# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
 # Note that the use of brackets around a tr range is ok here, (it's
 # even required, for portability to Solaris 10's /usr/bin/tr), since
 # the square bracket bytes happen to fall in the designated range.
 test $(git diff --cached --name-only --diff-filter=A -z $against |
   LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
 cat <<\EOF
Error: Attempt to add a non-ASCII file name.
This can cause problems if you want to work with people on other platforms.
To be portable it is advisable to rename the file.
If you know what you are doing you can disable this check using:
git config hooks.allownonascii true
EOF
 exit 1
fi

pythonfiles=$(find . -type f -name "*.py" | xargs git diff --cached --name-only $against | awk '{print $1}' | paste -d' ' -s)
echo "Started pre-commit git hook"
echo "**********************BLACK**********************"
if [ -z "$pythonfiles" ]
then
  echo "No changes in pythonfiles"
else
  pip install -q autoflake docformatter black
  autoflake -i --expand-star-imports --remove-all-unused-imports --ignore-init-module-imports --remove-duplicate-keys --remove-unused-variables $pythonfiles
  docformatter -i --make-summary-multi-line --pre-summary-newline  $pythonfiles
  isort $pythonfiles
  black $pythonfiles -l 79
  ret=$?
  if [ $ret -ne 0 ]; then
      echo "Error committing changes: Please format (black) your code."
      exit 1
  fi
  git add $pythonfiles
fi
echo "********************FLAKE8***********************"
if [ -z "$pythonfiles" ]
then
  echo "No changes in pythonfiles"
else
  pip install -q wemake-python-styleguide
  wget "https://raw.githubusercontent.com/ebot7/eb7-styleguide/master/settings/setup_ml_githooks.cfg"
  echo $pythonfiles
  flake8 $pythonfiles --config=setup_ml_githooks.cfg
  ret=$?
  rm setup_ml_githooks.cfg
  if [ $ret -ne 0 ]; then
          echo "Error committing changes: Please check syntax errors."
          exit 1
  fi
fi
echo "*************************************************"
echo "Ended pre-commit git hook"
